# Generated by Django 5.1.7 on 2025-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrolls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="payroll",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
